### ISSUE TITLE
CornerRadious attr not working

### ISSUE THREAD

**Issue by alvarochvz** [diogobernardino/RossDeckView#8]
Hi!

Lite version of DeckView! Excellent.

I am trying make it a deck of cardViews. When I try to add the radious in the XML it doesnt apply when I compile it.

I am not shure if I am doing something wrong.

Some enlightment please.

PS: Sorry for my bad english

**Comment by diogobernardino** [comment]
Are you perhaps applying the radius to the `RossDeckView `instead of the view inside? For instance, if you have a `CardView `inside `RossDeckView`, the radius needs to be applied to the `CardView`.
In the sample application, if I had to apply radius I would do it in `RelativeLayout `under _item.xml_.

**Comment by alvarochvz** [comment]
I added the properties inside the `CardView`.

I managed to solve it by adding `android:background="@android:color/transparent"` 
to my RelativeLayout and inside of it I put my cardview with the desired properties.

This gave me the result I wanted.

Thanks for the reply.
